# Generated by Django 5.1 on 2024-08-20 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ldn_Bank_Product_Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("v_prod_code", models.CharField(max_length=50, unique=True)),
                ("v_prod_name", models.CharField(max_length=100)),
                ("v_prod_type", models.CharField(max_length=50)),
                ("v_prod_group", models.CharField(max_length=50)),
                ("v_prod_group_desc", models.CharField(max_length=255)),
                ("v_prod_segment", models.CharField(max_length=100)),
                ("v_balance_sheet_category", models.CharField(max_length=50)),
                ("v_balance_sheet_category_desc", models.CharField(max_length=255)),
                ("v_prod_type_desc", models.CharField(max_length=255)),
                ("v_prod_desc", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Ldn_Customer_Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("v_party_id", models.CharField(max_length=50, unique=True)),
                ("fic_mis_date", models.DateField()),
                ("v_partner_code", models.CharField(max_length=50)),
                ("v_party_type", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "Ldn_Customer_Info",
            },
        ),
        migrations.CreateModel(
            name="Ldn_Financial_Instruments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("v_account_number", models.CharField(max_length=255, unique=True)),
                ("d_last_payment_date", models.DateField(null=True)),
                ("d_revised_maturity_date", models.DateField(null=True)),
                ("d_maturity_date", models.DateField(null=True)),
                ("d_orig_maturity_date", models.DateField(null=True)),
                ("d_start_date_p", models.DateField(null=True)),
                ("d_start_date_i", models.DateField(null=True)),
                ("d_start_date", models.DateField(null=True)),
                ("d_next_payment_date", models.DateField(null=True)),
                (
                    "n_cnr",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "n_allocated_cost",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "n_commitment_fee",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "n_maturity_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "n_eop_curr_prin_bal",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "n_eop_int_bal",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "n_eop_bal",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "n_current_fees",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("n_delinquent_days", models.IntegerField(null=True)),
                ("v_interest_freq_unit", models.CharField(max_length=50, null=True)),
                ("v_interest_payment_type", models.CharField(max_length=50, null=True)),
                (
                    "n_pd_percent",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "n_lgd_percent",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "n_ccf_percent",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "n_acct_risk_score",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("n_amrt_term", models.IntegerField(null=True)),
                ("v_amrt_term_unit", models.CharField(max_length=50, null=True)),
                ("v_interest_method", models.CharField(max_length=50, null=True)),
                ("v_ccy_code", models.CharField(max_length=10, null=True)),
                ("v_loan_type", models.CharField(max_length=50, null=True)),
                ("v_lob_code", models.CharField(max_length=50, null=True)),
                ("v_lv_code", models.CharField(max_length=50, null=True)),
                ("v_country_id", models.CharField(max_length=50, null=True)),
                (
                    "v_credit_score",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("v_coll_ccy", models.CharField(max_length=10, null=True)),
                ("v_collateral_type", models.CharField(max_length=50, null=True)),
                (
                    "n_effective_interest_rate",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("d_orig_next_payment_date", models.DateField(null=True)),
                ("fic_mis_date", models.DateField(null=True)),
                (
                    "n_fees_eir",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("v_account_group_id", models.CharField(max_length=50, null=True)),
                ("v_loan_desc", models.CharField(max_length=255, null=True)),
                (
                    "n_amortized_cost",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "n_market_value",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "n_twelvemonths_pd_percent",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "n_guaranteed_amt",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("v_loan_default_reason", models.CharField(max_length=255, null=True)),
                ("d_past_due_date", models.DateField(null=True)),
                (
                    "n_ifrs9_provision_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "n_fees",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "v_account_classification_cd",
                    models.CharField(max_length=50, null=True),
                ),
                ("v_day_count_ind", models.CharField(max_length=10, null=True)),
                ("v_gaap_code", models.CharField(max_length=50, null=True)),
                ("v_repayment_type", models.CharField(max_length=50, null=True)),
                (
                    "n_accrued_interest",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "n_curr_payment_recd",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "n_curr_interest_rate",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "n_undrawn_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("v_branch_code", models.CharField(max_length=50, null=True)),
                ("v_cust_ref_code", models.CharField(max_length=50, null=True)),
                ("v_prod_code", models.CharField(max_length=50, null=True)),
            ],
            options={
                "db_table": "Ldn_Financial_Instruments",
            },
        ),
        migrations.CreateModel(
            name="Ldn_LGD_Term_Structure",
            fields=[
                (
                    "v_lgd_term_structure_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("v_lgd_term_structure_name", models.CharField(max_length=255)),
                ("v_lgd_term_structure_desc", models.TextField()),
                ("v_lgd_term_frequency_unit", models.CharField(max_length=1)),
                ("n_lgd_percent", models.DecimalField(decimal_places=4, max_digits=5)),
                ("fic_mis_date", models.DateField()),
                ("v_data_source_code", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "Ldn_lgd_term_structure",
            },
        ),
        migrations.CreateModel(
            name="Ldn_Acct_Recovery_Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("v_account_number", models.CharField(max_length=50)),
                ("fic_mis_date", models.DateField()),
                ("d_recovery_date", models.DateField()),
                ("v_recovery_type_code", models.CharField(max_length=20)),
                (
                    "n_prin_recovery_amt",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=22, null=True
                    ),
                ),
                (
                    "n_int_recovery_amt",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=22, null=True
                    ),
                ),
                (
                    "n_charge_recovery_amt",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=22, null=True
                    ),
                ),
                (
                    "v_recovery_stage_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "n_cost_case_filed",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=22, null=True
                    ),
                ),
                (
                    "v_iso_currency_cd",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                ("v_lv_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "n_recovery_income_amt",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=22, null=True
                    ),
                ),
                (
                    "v_data_source_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
            options={
                "db_table": "ldn_acct_recovery_details",
                "unique_together": {
                    ("v_account_number", "fic_mis_date", "d_recovery_date")
                },
            },
        ),
        migrations.CreateModel(
            name="Ldn_Customer_Rating_Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fic_mis_date", models.DateField()),
                ("v_rating_src_code", models.CharField(max_length=50)),
                ("v_party_cd", models.CharField(max_length=50)),
                ("v_purpose", models.CharField(max_length=50)),
                ("v_rating_code", models.CharField(max_length=50)),
                ("v_data_origin", models.CharField(max_length=50)),
                ("v_credit_reason_code", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "Ldn_Customer_Rating_Details",
                "unique_together": {("fic_mis_date", "v_party_cd")},
            },
        ),
        migrations.CreateModel(
            name="Ldn_Exchange_Rates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fic_mis_date", models.DateField()),
                ("v_from_ccy_code", models.CharField(max_length=3)),
                ("v_to_ccy_code", models.CharField(max_length=3)),
                (
                    "n_exchange_rate",
                    models.DecimalField(decimal_places=6, max_digits=15),
                ),
            ],
            options={
                "db_table": "Ldn_exchange_rates",
                "unique_together": {
                    ("fic_mis_date", "v_from_ccy_code", "v_to_ccy_code")
                },
            },
        ),
        migrations.CreateModel(
            name="Ldn_Expected_Cashflows",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fic_mis_date", models.DateField()),
                ("v_account_number", models.CharField(max_length=50)),
                ("d_cash_flow_date", models.DateField()),
                (
                    "n_cash_flow_amount",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("v_financial_element_code", models.CharField(max_length=10)),
                ("v_iso_ccy_code", models.CharField(max_length=3)),
            ],
            options={
                "db_table": "Ldn_expected_cashflows",
                "unique_together": {
                    ("fic_mis_date", "v_account_number", "d_cash_flow_date")
                },
            },
        ),
        migrations.CreateModel(
            name="Ldn_PD_Term_Structure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "v_pd_term_structure_id",
                    models.CharField(max_length=100, unique=True),
                ),
                ("v_pd_term_structure_name", models.CharField(max_length=255)),
                ("v_pd_term_structure_desc", models.TextField(blank=True, null=True)),
                (
                    "v_pd_term_frequency_unit",
                    models.CharField(
                        choices=[
                            ("M", "Monthly"),
                            ("Q", "Quarterly"),
                            ("H", "Half Yearly"),
                            ("Y", "Yearly"),
                            ("D", "Daily"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "v_pd_term_structure_type",
                    models.CharField(
                        choices=[("R", "Rating"), ("D", "DPD")], max_length=1
                    ),
                ),
                (
                    "v_default_probability_type",
                    models.CharField(
                        choices=[("M", "Marginal"), ("C", "Cumulative")], max_length=1
                    ),
                ),
                ("fic_mis_date", models.DateField()),
                ("n_pd_term_frequency", models.PositiveIntegerField()),
                ("v_data_source_code", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "Ldn_pd_term_structure",
                "unique_together": {("v_pd_term_structure_id", "fic_mis_date")},
            },
        ),
        migrations.CreateModel(
            name="Ldn_Recovery_Cashflows",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fic_mis_date", models.DateField()),
                ("v_account_number", models.CharField(max_length=50)),
                ("d_cash_flow_date", models.DateField()),
                (
                    "n_cash_flow_amount",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("v_financial_element_code", models.CharField(max_length=10)),
                ("v_iso_ccy_code", models.CharField(max_length=3)),
            ],
            options={
                "db_table": "Ldn_Recovery_Cashflows",
                "unique_together": {
                    ("fic_mis_date", "v_account_number", "d_cash_flow_date")
                },
            },
        ),
        migrations.CreateModel(
            name="Ldn_PD_Term_Structure_Dtl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fic_mis_date", models.DateField()),
                ("v_credit_risk_basis_cd", models.CharField(max_length=100)),
                ("n_period_applicable", models.PositiveIntegerField()),
                ("n_pd_percent", models.DecimalField(decimal_places=4, max_digits=5)),
                ("v_scenario_cd", models.CharField(max_length=50)),
                ("v_data_source_code", models.CharField(max_length=50)),
                (
                    "v_pd_term_structure_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="term_structure_details",
                        to="IFRS9.ldn_pd_term_structure",
                    ),
                ),
            ],
            options={
                "db_table": "Ldn_pd_term_structure_dtl",
                "unique_together": {
                    (
                        "v_pd_term_structure_id",
                        "fic_mis_date",
                        "v_credit_risk_basis_cd",
                        "n_period_applicable",
                        "v_scenario_cd",
                    )
                },
            },
        ),
    ]
