# Generated by Django 5.1 on 2024-10-30 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ldn_financial_instrument",
            unique_together={("fic_mis_date", "v_account_number")},
        ),
    ]
