# Generated by Django 5.1 on 2024-08-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Ldn_Acct_Recovery_Details",
            new_name="Ldn_Acct_Recovery_Detail",
        ),
        migrations.RenameModel(
            old_name="Ldn_Customer_Rating_Details",
            new_name="Ldn_Customer_Rating_Detail",
        ),
        migrations.RenameModel(
            old_name="Ldn_Exchange_Rates",
            new_name="Ldn_Exchange_Rate",
        ),
        migrations.RenameModel(
            old_name="Ldn_Expected_Cashflows",
            new_name="Ldn_Expected_Cashflow",
        ),
        migrations.RenameModel(
            old_name="Ldn_Financial_Instruments",
            new_name="Ldn_Financial_Instrument",
        ),
        migrations.RenameModel(
            old_name="Ldn_Recovery_Cashflows",
            new_name="Ldn_Recovery_Cashflow",
        ),
        migrations.AlterModelTable(
            name="ldn_acct_recovery_detail",
            table="ldn_acct_recovery_detail",
        ),
        migrations.AlterModelTable(
            name="ldn_customer_rating_detail",
            table="Ldn_Customer_Rating_Detail",
        ),
        migrations.AlterModelTable(
            name="ldn_exchange_rate",
            table="Ldn_exchange_rate",
        ),
        migrations.AlterModelTable(
            name="ldn_expected_cashflow",
            table="Ldn_expected_cashflow",
        ),
        migrations.AlterModelTable(
            name="ldn_financial_instrument",
            table="Ldn_Financial_Instrument",
        ),
        migrations.AlterModelTable(
            name="ldn_recovery_cashflow",
            table="Ldn_Recovery_Cashflow",
        ),
    ]
