# Generated by Django 5.1 on 2024-08-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "IFRS9",
            "0002_rename_ldn_acct_recovery_details_ldn_acct_recovery_detail_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TableMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "table_type",
                    models.CharField(
                        choices=[
                            ("FACT", "Fact Table"),
                            ("DIM", "Dimension Table"),
                            ("REF", "Reference Table"),
                            ("STG", "Staging Table"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
