# Generated by Django 5.1 on 2024-08-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0003_tablemetadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ldn_bank_product_info",
            name="v_prod_desc",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="ldn_lgd_term_structure",
            name="v_lgd_term_structure_desc",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="ldn_pd_term_structure",
            name="v_pd_term_structure_desc",
            field=models.CharField(default=-1212, max_length=50),
            preserve_default=False,
        ),
    ]
