# Generated by Django 5.1 on 2024-09-02 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0004_alter_ldn_bank_product_info_v_prod_desc_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ldn_expected_cashflow",
            old_name="v_financial_element_code",
            new_name="V_CASH_FLOW_TYPE",
        ),
        migrations.RenameField(
            model_name="ldn_expected_cashflow",
            old_name="v_iso_ccy_code",
            new_name="V_CCY_CODE",
        ),
        migrations.RenameField(
            model_name="ldn_recovery_cashflow",
            old_name="v_financial_element_code",
            new_name="V_CASH_FLOW_TYPE",
        ),
        migrations.RenameField(
            model_name="ldn_recovery_cashflow",
            old_name="v_iso_ccy_code",
            new_name="V_CCY_CODE",
        ),
    ]
