# Generated by Django 5.1 on 2024-10-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0004_alter_ldn_financial_instrument_v_account_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ldn_bank_product_info",
            name="fic_mis_date",
            field=models.DateField(default='2023-01-01'),
            preserve_default=False,
        ),
    ]
