# Generated by Django 5.1 on 2024-10-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0005_ldn_bank_product_info_fic_mis_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ldn_customer_rating_detail",
            name="v_party_cd",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
