# Generated by Django 5.1 on 2024-09-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0006_remove_ldn_financial_instrument_d_orig_maturity_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ldn_financial_instrument",
            name="n_amrt_term",
        ),
        migrations.AddField(
            model_name="ldn_financial_instrument",
            name="m_fees",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="ldn_financial_instrument",
            name="v_m_fees_term_unit",
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.CreateModel(
            name="FSI_Expected_Cashflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fic_mis_date", models.DateField()),
                ("v_account_number", models.CharField(max_length=50)),
                ("n_cash_flow_bucket", models.IntegerField()),
                ("d_cash_flow_date", models.DateField()),
                (
                    "N_PRINCIPAL_RUN_OFF",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "N_INTEREST_RUN_OFF",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "n_cash_flow_amount",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("n_balance", models.DecimalField(decimal_places=2, max_digits=20)),
                ("V_CASH_FLOW_TYPE", models.CharField(max_length=10)),
                ("V_CCY_CODE", models.CharField(max_length=3)),
            ],
            options={
                "db_table": "FSI_Expected_Cashflow",
                "unique_together": {
                    ("fic_mis_date", "v_account_number", "d_cash_flow_date")
                },
            },
        ),
    ]
