# Generated by Django 5.1 on 2024-11-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0006_alter_ldn_customer_rating_detail_v_party_cd"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="fsi_product_segment",
            name="unique_segment_type_desc",
        ),
        migrations.AddConstraint(
            model_name="fsi_product_segment",
            constraint=models.UniqueConstraint(
                fields=("v_prod_segment", "v_prod_type"),
                name="unique_segment_type_desc",
            ),
        ),
    ]
