# Generated by Django 5.1 on 2024-11-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0007_remove_fsi_product_segment_unique_segment_type_desc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fsi_product_segment",
            name="v_prod_desc",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
