# Generated by Django 5.1 on 2024-09-02 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0007_remove_ldn_financial_instrument_n_amrt_term_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fsi_expected_cashflow",
            old_name="N_INTEREST_RUN_OFF",
            new_name="n_interest_payment",
        ),
        migrations.RenameField(
            model_name="fsi_expected_cashflow",
            old_name="N_PRINCIPAL_RUN_OFF",
            new_name="n_principal_payment",
        ),
    ]
