# Generated by Django 5.1 on 2024-11-05 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0008_alter_fsi_product_segment_v_prod_desc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ldn_pd_term_structure",
            name="v_default_probability_type",
        ),
    ]
