# Generated by Django 5.1 on 2024-09-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "IFRS9",
            "0008_rename_n_interest_run_off_fsi_expected_cashflow_n_interest_payment_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Ldn_Payment_Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fic_mis_date", models.DateField()),
                ("v_account_number", models.CharField(max_length=50)),
                ("d_payment_date", models.DateField()),
                (
                    "n_principal_payment_amt",
                    models.DecimalField(decimal_places=3, max_digits=22, null=True),
                ),
                (
                    "n_interest_payment_amt",
                    models.DecimalField(decimal_places=3, max_digits=22, null=True),
                ),
                (
                    "n_amount",
                    models.DecimalField(decimal_places=3, max_digits=22, null=True),
                ),
                ("v_payment_type_cd", models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
