# Generated by Django 5.1 on 2024-11-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0009_remove_ldn_pd_term_structure_v_default_probability_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ldn_lgd_term_structure",
            name="v_lgd_term_structure_desc",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
