# Generated by Django 5.1 on 2024-09-06 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0009_ldn_payment_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="FSI_LLFP_APP_PREFERENCES",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pd_interpolation_method",
                    models.CharField(
                        blank=True, default="NL-POISSON", max_length=100, null=True
                    ),
                ),
                ("n_pd_model_proj_cap", models.IntegerField(default=25)),
                ("llfp_bucket_length", models.CharField(default="M", max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="Ldn_PD_Term_Structure_Interpolated",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bucket_id", models.IntegerField()),
                ("marginal_pd", models.DecimalField(decimal_places=6, max_digits=10)),
                ("cumulative_pd", models.DecimalField(decimal_places=6, max_digits=10)),
                (
                    "v_cash_flow_bucket_unit",
                    models.CharField(
                        choices=[("M", "Monthly"), ("Q", "Quarterly")], max_length=1
                    ),
                ),
                (
                    "v_pd_term_structure_dtl",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interpolated_pd",
                        to="IFRS9.ldn_pd_term_structure_dtl",
                    ),
                ),
            ],
            options={
                "db_table": "Ldn_pd_term_structure_interpolated",
                "unique_together": {
                    ("v_pd_term_structure_dtl", "bucket_id", "v_cash_flow_bucket_unit")
                },
            },
        ),
    ]
