# Generated by Django 5.1 on 2024-09-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0010_fsi_llfp_app_preferences_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FSI_PD_Interpolated",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "v_int_rating_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "v_delq_band_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("v_pd_term_structure_type", models.CharField(max_length=3)),
                (
                    "n_pd_percent",
                    models.DecimalField(decimal_places=11, max_digits=15, null=True),
                ),
                (
                    "n_per_period_default_prob",
                    models.DecimalField(decimal_places=11, max_digits=15, null=True),
                ),
                (
                    "n_cumulative_default_prob",
                    models.DecimalField(decimal_places=11, max_digits=15, null=True),
                ),
                ("v_cash_flow_bucket_id", models.IntegerField()),
                ("v_cash_flow_bucket_unit", models.CharField(max_length=1)),
                ("d_record_start_date", models.DateField()),
                ("d_record_end_date", models.DateField()),
            ],
            options={
                "db_table": "FSI_PD_Interpolated",
            },
        ),
        migrations.DeleteModel(
            name="Ldn_PD_Term_Structure_Interpolated",
        ),
    ]
