# Generated by Django 5.1 on 2024-11-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0010_alter_ldn_lgd_term_structure_v_lgd_term_structure_desc"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="functionexecutionstatus",
            options={"ordering": ["run_count", "execution_start_date"]},
        ),
        migrations.RemoveConstraint(
            model_name="functionexecutionstatus",
            name="unique_execution_process",
        ),
        migrations.RenameField(
            model_name="functionexecutionstatus",
            old_name="execution_date",
            new_name="execution_start_date",
        ),
        migrations.AddField(
            model_name="functionexecutionstatus",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="functionexecutionstatus",
            name="execution_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="functionexecutionstatus",
            constraint=models.UniqueConstraint(
                fields=("execution_start_date", "process_run_id", "function"),
                name="unique_execution_process",
            ),
        ),
    ]
