# Generated by Django 5.1 on 2024-11-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0011_alter_functionexecutionstatus_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fct_reporting_lines",
            name="n_pd_term_structure_name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
