# Generated by Django 5.1 on 2024-09-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0011_fsi_pd_interpolated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fsi_pd_interpolated",
            name="fic_mis_date",
            field=models.DateField(null=True),
        ),
    ]
