# Generated by Django 5.1 on 2024-09-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0012_fsi_pd_interpolated_fic_mis_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="fsi_pd_interpolated",
            name="v_pd_term_structure_id",
            field=models.CharField(default=1188, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fsi_llfp_app_preferences",
            name="llfp_bucket_length",
            field=models.CharField(
                choices=[
                    ("Y", "Yearly"),
                    ("H", "Half-Yearly"),
                    ("Q", "Quarterly"),
                    ("M", "Monthly"),
                ],
                default="Y",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="fsi_llfp_app_preferences",
            name="pd_interpolation_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NL-POISSON", "Non-Linear Poisson"),
                    ("NL-GEOMETRIC", "Non-Linear Geometric"),
                    ("NL-ARITHMETIC", "Non-Linear Arithmetic"),
                    ("EXPONENTIAL_DECAY", "Exponential Decay"),
                ],
                default="NL-POISSON",
                max_length=100,
                null=True,
            ),
        ),
    ]
