# Generated by Django 5.1 on 2024-11-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0013_alter_fct_reporting_lines_n_pd_term_structure_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coolingperioddefinition",
            name="v_amrt_term_unit",
            field=models.CharField(
                choices=[
                    ("D", "Daily"),
                    ("M", "Monthly"),
                    ("Q", "Quarterly"),
                    ("H", "Half-Yearly"),
                    ("Y", "Yearly"),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="fsi_dpd_stage_mapping",
            name="payment_frequency",
            field=models.CharField(
                choices=[
                    ("D", "Daily"),
                    ("Q", "Quarterly"),
                    ("H", "Half-Yearly"),
                    ("Y", "Yearly"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="ldn_lgd_term_structure",
            name="v_lgd_term_structure_id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
