# Generated by Django 5.1 on 2024-09-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0013_fsi_pd_interpolated_v_pd_term_structure_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fsi_pd_interpolated",
            name="v_pd_term_structure_id",
            field=models.CharField(max_length=100),
        ),
    ]
