# Generated by Django 5.1 on 2024-09-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0014_alter_fsi_pd_interpolated_v_pd_term_structure_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="fsi_llfp_app_preferences",
            name="interpolation_level",
            field=models.CharField(
                choices=[
                    ("ACCOUNT", "Account Level"),
                    ("TERM_STRUCTURE", "PD Term Structure Level"),
                ],
                default="TERM_STRUCTURE",
                max_length=20,
            ),
        ),
        
        migrations.CreateModel(
            name="FSI_PD_Account_Interpolated",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fic_mis_date", models.DateField()),
                ("v_account_number", models.CharField(max_length=50)),
                ("n_pd_percent", models.DecimalField(decimal_places=6, max_digits=10)),
                (
                    "n_per_period_default_prob",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                (
                    "n_cumulative_default_prob",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                ("v_cash_flow_bucket_id", models.IntegerField()),
                (
                    "v_cash_flow_bucket_unit",
                    models.CharField(
                        choices=[
                            ("M", "Monthly"),
                            ("Q", "Quarterly"),
                            ("H", "Half-Yearly"),
                            ("Y", "Yearly"),
                        ],
                        max_length=1,
                    ),
                ),
                ("d_record_start_date", models.DateField()),
                ("d_record_end_date", models.DateField()),
            ],
            options={
                "db_table": "fsi_pd_account_interpolated",
                "unique_together": {
                    ("fic_mis_date", "v_account_number", "v_cash_flow_bucket_id")
                },
            },
        ),
    ]
