# Generated by Django 5.1 on 2024-11-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0014_alter_coolingperioddefinition_v_amrt_term_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ldn_financial_instrument",
            name="v_account_number",
            field=models.CharField(max_length=255),
        ),
    ]
