# Generated by Django 5.1 on 2024-09-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0014_alter_fsi_pd_interpolated_v_pd_term_structure_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="fsi_llfp_app_preferences",
            name="interpolation_level",
            field=models.CharField(
                choices=[
                    ("ACCOUNT", "Account Level"),
                    ("TERM_STRUCTURE", "PD Term Structure Level"),
                ],
                default="TERM_STRUCTURE",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="fsi_Financial_Cash_Flow_Cal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("v_account_number", models.CharField(max_length=20)),
                ("d_cash_flow_date", models.DateField()),
                ("n_run_skey", models.BigIntegerField(default=-1)),
                ("fic_mis_date", models.DateField()),
                (
                    "n_principal_run_off",
                    models.DecimalField(decimal_places=3, max_digits=22, null=True),
                ),
                (
                    "n_interest_run_off",
                    models.DecimalField(decimal_places=3, max_digits=22, null=True),
                ),
                ("n_cash_flow_bucket_id", models.IntegerField(null=True)),
                (
                    "n_cash_flow_amount",
                    models.DecimalField(decimal_places=3, max_digits=22, null=True),
                ),
                (
                    "n_cumulative_loss_rate",
                    models.DecimalField(decimal_places=11, max_digits=15, null=True),
                ),
                (
                    "n_expected_cash_flow_rate",
                    models.DecimalField(decimal_places=11, max_digits=15, null=True),
                ),
                (
                    "n_discount_rate",
                    models.DecimalField(decimal_places=11, max_digits=15, null=True),
                ),
                (
                    "n_discount_factor",
                    models.DecimalField(decimal_places=11, max_digits=15, null=True),
                ),
                (
                    "n_expected_cash_flow",
                    models.DecimalField(decimal_places=3, max_digits=22, null=True),
                ),
                (
                    "n_effective_interest_rate",
                    models.DecimalField(decimal_places=11, max_digits=15, null=True),
                ),
                (
                    "n_lgd_percent",
                    models.DecimalField(decimal_places=11, max_digits=15, null=True),
                ),
                (
                    "n_expected_cash_flow_pv",
                    models.DecimalField(decimal_places=3, max_digits=22, null=True),
                ),
                (
                    "n_exposure_at_default",
                    models.DecimalField(decimal_places=3, max_digits=22, null=True),
                ),
                (
                    "n_forward_expected_loss",
                    models.DecimalField(decimal_places=3, max_digits=22, null=True),
                ),
                (
                    "n_forward_expected_loss_pv",
                    models.DecimalField(decimal_places=3, max_digits=22, null=True),
                ),
                ("n_interest_rate_cd", models.BigIntegerField(null=True)),
                ("v_ccy_code", models.CharField(max_length=3, null=True)),
                (
                    "n_cash_shortfall",
                    models.DecimalField(decimal_places=3, max_digits=22, null=True),
                ),
                (
                    "n_per_period_loss_rate",
                    models.DecimalField(decimal_places=11, max_digits=15, null=True),
                ),
                (
                    "n_cash_shortfall_pv",
                    models.DecimalField(decimal_places=3, max_digits=22, null=True),
                ),
                (
                    "n_per_period_loss_pv",
                    models.DecimalField(decimal_places=3, max_digits=22, null=True),
                ),
                (
                    "n_cash_flow_fwd_pv",
                    models.DecimalField(decimal_places=3, max_digits=22, null=True),
                ),
                (
                    "n_forward_exposure_amt",
                    models.DecimalField(decimal_places=3, max_digits=22, null=True),
                ),
                (
                    "n_per_period_impaired_prob",
                    models.DecimalField(decimal_places=11, max_digits=15, null=True),
                ),
                (
                    "n_cumulative_impaired_prob",
                    models.DecimalField(decimal_places=11, max_digits=15, null=True),
                ),
                (
                    "n_12m_per_period_pd",
                    models.DecimalField(decimal_places=11, max_digits=15, null=True),
                ),
                (
                    "n_12m_cumulative_pd",
                    models.DecimalField(decimal_places=11, max_digits=15, null=True),
                ),
                (
                    "n_12m_exp_cash_flow",
                    models.DecimalField(decimal_places=3, max_digits=22, null=True),
                ),
                (
                    "n_12m_exp_cash_flow_pv",
                    models.DecimalField(decimal_places=3, max_digits=22, null=True),
                ),
                (
                    "n_12m_cash_shortfall",
                    models.DecimalField(decimal_places=3, max_digits=22, null=True),
                ),
                (
                    "n_12m_cash_shortfall_pv",
                    models.DecimalField(decimal_places=3, max_digits=22, null=True),
                ),
                (
                    "n_12m_fwd_expected_loss",
                    models.DecimalField(decimal_places=3, max_digits=22, null=True),
                ),
                (
                    "n_12m_fwd_expected_loss_pv",
                    models.DecimalField(decimal_places=3, max_digits=22, null=True),
                ),
            ],
            options={
                "db_table": "fsi_Financial_Cash_Flow_Cal",
                "unique_together": {
                    (
                        "v_account_number",
                        "d_cash_flow_date",
                        "fic_mis_date",
                        "n_run_skey",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="FSI_PD_Account_Interpolated",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fic_mis_date", models.DateField()),
                ("v_account_number", models.CharField(max_length=50)),
                ("n_pd_percent", models.DecimalField(decimal_places=6, max_digits=10)),
                (
                    "n_per_period_default_prob",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                (
                    "n_cumulative_default_prob",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                ("v_cash_flow_bucket_id", models.IntegerField()),
                (
                    "v_cash_flow_bucket_unit",
                    models.CharField(
                        choices=[
                            ("M", "Monthly"),
                            ("Q", "Quarterly"),
                            ("H", "Half-Yearly"),
                            ("Y", "Yearly"),
                        ],
                        max_length=1,
                    ),
                ),
                ("d_record_start_date", models.DateField()),
                ("d_record_end_date", models.DateField()),
            ],
            options={
                "db_table": "fsi_pd_account_interpolated",
                "unique_together": {
                    ("fic_mis_date", "v_account_number", "v_cash_flow_bucket_id")
                },
            },
        ),
    ]
