# Generated by Django 5.1 on 2024-11-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0015_alter_ldn_financial_instrument_v_account_number"),
    ]

    operations = [
        
        migrations.AlterField(
            model_name="fsi_financial_cash_flow_cal",
            name="n_run_skey",
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="ldn_financial_instrument",
            name="d_maturity_date",
            field=models.DateField(default='1212-12-12'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ldn_financial_instrument",
            name="n_curr_interest_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0.1,
                help_text="Fixed interest rate for the loan",
                max_digits=5,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ldn_financial_instrument",
            name="n_eop_bal",
            field=models.DecimalField(decimal_places=2, default=1188, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="ldn_payment_schedule",
            unique_together={("fic_mis_date", "v_account_number", "d_payment_date")},
        ),
    ]
