# Generated by Django 5.1 on 2024-09-07 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0015_fsi_llfp_app_preferences_interpolation_level_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fsi_pd_account_interpolated",
            name="d_record_end_date",
        ),
        migrations.RemoveField(
            model_name="fsi_pd_account_interpolated",
            name="d_record_start_date",
        ),
        migrations.RemoveField(
            model_name="fsi_pd_interpolated",
            name="d_record_end_date",
        ),
        migrations.RemoveField(
            model_name="fsi_pd_interpolated",
            name="d_record_start_date",
        ),
    ]
