# Generated by Django 5.1 on 2024-09-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0016_remove_fsi_pd_account_interpolated_d_record_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ldn_financial_instrument",
            name="n_interest_changing_rate",
            field=models.DecimalField(
                decimal_places=4,
                help_text="Changing interest rate value, e.g., LIBOR rate at a specific time",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ldn_financial_instrument",
            name="v_management_fee_rate",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Annual management fee rate, e.g., 1%",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ldn_financial_instrument",
            name="n_curr_interest_rate",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Fixed interest rate for the loan",
                max_digits=5,
                null=True,
            ),
        ),
    ]
