# Generated by Django 5.1 on 2024-09-08 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0017_ldn_financial_instrument_n_interest_changing_rate_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ldn_financial_instrument",
            old_name="v_repayment_type",
            new_name="v_amrt_repayment_type",
        ),
    ]
