# Generated by Django 5.1 on 2024-09-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "IFRS9",
            "0018_rename_v_repayment_type_ldn_financial_instrument_v_amrt_repayment_type",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Fsi_Interest_Method",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "v_interest_method",
                    models.CharField(
                        choices=[
                            ("Simple", "Simple Interest"),
                            ("Compound", "Compound Interest"),
                            ("Amortized", "Amortized Interest"),
                            ("Floating", "Floating/Variable Interest"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
