# Generated by Django 5.1 on 2024-09-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0019_fsi_interest_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="ldn_financial_instrument",
            name="n_wht_percent",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
