# Generated by Django 5.1 on 2024-12-06 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0020_coolingperioddefinition_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ldn_lgd_term_structure",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="fsi_dpd_stage_mapping",
            name="payment_frequency",
            field=models.CharField(
                choices=[
                    ("D", "Daily"),
                    ("M", "Monthly"),
                    ("Q", "Quarterly"),
                    ("H", "Half-Yearly"),
                    ("Y", "Yearly"),
                ],
                max_length=50,
            ),
        ),
    ]
