# Generated by Django 5.1 on 2024-09-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0020_ldn_financial_instrument_n_wht_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="ldn_financial_instrument",
            name="v_day_count_ind",
            field=models.CharField(
                default="30/365",
                help_text="This column stores the accrual basis code for interest accrual calculation.",
                max_length=7,
            ),
        ),
    ]
