# Generated by Django 5.1 on 2024-09-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0021_ldn_financial_instrument_v_day_count_ind"),
    ]

    operations = [
        migrations.CreateModel(
            name="FSI_Product_Segment",
            fields=[
                ("segment_id", models.AutoField(primary_key=True, serialize=False)),
                ("v_prod_segment", models.CharField(max_length=100)),
                ("v_prod_type", models.CharField(editable=False, max_length=255)),
                ("v_prod_desc", models.TextField(editable=False)),
            ],
            options={
                "db_table": "fsi_product_segment",
            },
        ),
        migrations.RemoveField(
            model_name="ldn_lgd_term_structure",
            name="v_lgd_term_frequency_unit",
        ),
        migrations.AlterField(
            model_name="ldn_lgd_term_structure",
            name="v_lgd_term_structure_desc",
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AddConstraint(
            model_name="ldn_lgd_term_structure",
            constraint=models.UniqueConstraint(
                fields=("v_lgd_term_structure_id", "fic_mis_date"),
                name="unique_term_structure_id_date",
            ),
        ),
        migrations.AlterModelTable(
            name="ldn_lgd_term_structure",
            table="ldn_lgd_term_structure",
        ),
        migrations.AddConstraint(
            model_name="fsi_product_segment",
            constraint=models.UniqueConstraint(
                fields=("v_prod_segment", "v_prod_type", "v_prod_desc"),
                name="unique_segment_type_desc",
            ),
        ),
    ]
