# Generated by Django 5.1 on 2025-01-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0021_ldn_lgd_term_structure_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fct_stage_determination",
            name="n_pd_term_structure_name",
            field=models.CharField(default=1188, editable=False, max_length=50),
            preserve_default=False,
        ),
    ]
