# Generated by Django 5.1 on 2025-01-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0022_alter_fct_stage_determination_n_pd_term_structure_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fct_reporting_lines",
            name="n_pd_term_structure_name",
            field=models.CharField(default=1188, editable=False, max_length=50),
            preserve_default=False,
        ),
    ]
