# Generated by Django 5.1 on 2025-01-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0023_alter_fct_reporting_lines_n_pd_term_structure_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fct_stage_determination",
            name="n_credit_rating_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="fct_stage_determination",
            name="n_in_cooling_period_flag",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="fct_stage_determination",
            name="n_loan_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="fct_stage_determination",
            name="n_org_credit_score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="fct_stage_determination",
            name="n_partner_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="fct_stage_determination",
            name="n_party_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="fct_stage_determination",
            name="n_pd_term_structure_desc",
            field=models.CharField(
                blank=True, editable=False, max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="fct_stage_determination",
            name="n_pd_term_structure_name",
            field=models.CharField(
                blank=True, editable=False, max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="fct_stage_determination",
            name="n_prod_desc",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="fct_stage_determination",
            name="n_prod_segment",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
