# Generated by Django 5.1 on 2024-09-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0023_alter_fsi_product_segment_v_prod_desc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fsi_product_segment",
            name="v_prod_desc",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="fsi_product_segment",
            name="v_prod_segment",
            field=models.CharField(max_length=255),
        ),
    ]
