# Generated by Django 5.1 on 2024-09-10 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0024_alter_fsi_product_segment_v_prod_desc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ldn_lgd_term_structure",
            name="v_lgd_term_structure_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="IFRS9.fsi_product_segment",
            ),
        ),
    ]
