# Generated by Django 5.1 on 2025-01-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0024_alter_fct_stage_determination_n_credit_rating_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fct_stage_determination",
            name="n_ecl_compute_ind",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
