# Generated by Django 5.1 on 2024-09-10 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0025_alter_ldn_lgd_term_structure_v_lgd_term_structure_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ldn_pd_term_structure",
            name="v_pd_term_structure_desc",
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name="ldn_pd_term_structure",
            name="v_pd_term_structure_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="IFRS9.fsi_product_segment",
            ),
        ),
        migrations.AlterModelTable(
            name="ldn_pd_term_structure",
            table="ldn_pd_term_structure",
        ),
    ]
