# Generated by Django 5.1 on 2025-01-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0025_alter_fct_stage_determination_n_ecl_compute_ind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fct_reporting_lines",
            name="n_in_cooling_period_flag",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="fct_reporting_lines",
            name="n_partner_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="fct_reporting_lines",
            name="n_party_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="fct_reporting_lines",
            name="n_pd_term_structure_desc",
            field=models.CharField(
                blank=True, editable=False, max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="fct_reporting_lines",
            name="n_pd_term_structure_name",
            field=models.CharField(
                blank=True, editable=False, max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="fct_reporting_lines",
            name="n_prod_desc",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="fct_reporting_lines",
            name="n_prod_segment",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
