# Generated by Django 5.1 on 2025-01-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0026_alter_fct_reporting_lines_n_in_cooling_period_flag_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ldn_financial_instrument",
            options={"permissions": [("can_load_data", "Can load data")]},
        ),
    ]
