# Generated by Django 5.1 on 2024-09-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0026_alter_ldn_pd_term_structure_v_pd_term_structure_desc_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ldn_financial_instrument",
            old_name="n_acct_risk_score",
            new_name="n_curr_credit_score",
        ),
        migrations.AddField(
            model_name="ldn_financial_instrument",
            name="n_collateral_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="ldn_financial_instrument",
            name="v_credit_rating_code",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="FCT_Stage_Determination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fic_mis_date", models.BigIntegerField(blank=True)),
                ("n_account_number", models.BigIntegerField()),
                ("d_acct_start_date", models.DateField(blank=True, null=True)),
                ("d_last_payment_date", models.DateField(blank=True, null=True)),
                ("d_last_reprice_date", models.DateField(blank=True, null=True)),
                ("d_next_payment_date", models.DateField(blank=True, null=True)),
                ("d_revised_maturity_date", models.DateField(blank=True, null=True)),
                ("n_accrual_basis_code", models.IntegerField(blank=True, null=True)),
                (
                    "n_acct_classification_skey",
                    models.IntegerField(blank=True, null=True),
                ),
                ("n_amrt_term", models.IntegerField(blank=True, null=True)),
                (
                    "n_carrying_amount_ncy",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=22, null=True
                    ),
                ),
                (
                    "n_curr_payment_recd",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=22, null=True
                    ),
                ),
                ("n_cust_ref_code", models.CharField(max_length=50, null=True)),
                ("n_cust_type_skey", models.BigIntegerField(blank=True, null=True)),
                ("n_delinquent_days", models.IntegerField(blank=True, null=True)),
                ("n_delq_band_skey", models.BigIntegerField(blank=True, null=True)),
                (
                    "n_delq_impaired_state_skey",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "n_curr_interest_rate",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=11, null=True
                    ),
                ),
                (
                    "n_effective_interest_rate",
                    models.DecimalField(
                        blank=True, decimal_places=11, max_digits=15, null=True
                    ),
                ),
                (
                    "v_interest_freq_unit",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "v_interest_method",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                (
                    "n_accrued_interest",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=22, null=True
                    ),
                ),
                (
                    "n_rate_chg_min",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "n_exposure_at_default",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=22, null=True
                    ),
                ),
                (
                    "n_exposure_limit",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=22, null=True
                    ),
                ),
                (
                    "n_eop_prin_bal",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=22, null=True
                    ),
                ),
                (
                    "n_lgd_percent",
                    models.DecimalField(
                        blank=True, decimal_places=11, max_digits=15, null=True
                    ),
                ),
                (
                    "n_twelve_months_orig_pd",
                    models.DecimalField(
                        blank=True, decimal_places=11, max_digits=15, null=True
                    ),
                ),
                (
                    "n_lifetime_orig_pd",
                    models.DecimalField(
                        blank=True, decimal_places=11, max_digits=15, null=True
                    ),
                ),
                (
                    "n_twelve_months_pd",
                    models.DecimalField(
                        blank=True, decimal_places=11, max_digits=15, null=True
                    ),
                ),
                (
                    "n_lifetime_pd",
                    models.DecimalField(
                        blank=True, decimal_places=11, max_digits=15, null=True
                    ),
                ),
                (
                    "n_pd_term_structure_skey",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "n_12m_pd_change",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=22, null=True
                    ),
                ),
                ("n_prod_code", models.BigIntegerField(blank=True, null=True)),
                ("n_prod_type_skey", models.BigIntegerField(blank=True, null=True)),
                (
                    "n_rating_impaired_state_skey",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("v_amrt_repayment_type", models.CharField(max_length=50, null=True)),
                ("n_remain_no_of_pmts", models.BigIntegerField(blank=True, null=True)),
                (
                    "v_amrt_term_unit",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("v_ccy_code", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "v_common_coa_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("v_gl_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "n_curr_ifrs_stage_skey",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "n_prev_ifrs_stage_skey",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("n_country_skey", models.BigIntegerField(blank=True, null=True)),
                ("n_segment_skey", models.BigIntegerField(blank=True, null=True)),
                ("n_ecl_compute_ind", models.IntegerField(default=0)),
                ("n_credit_rating_code", models.CharField(max_length=50, null=True)),
                ("n_curr_credit_score", models.IntegerField(blank=True, null=True)),
                ("n_acct_rating_movement", models.IntegerField(blank=True, null=True)),
                ("n_party_rating_movement", models.IntegerField(blank=True, null=True)),
                (
                    "n_conditionally_cancel_flag",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "n_collateral_amount",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=22, null=True
                    ),
                ),
                ("n_loan_type", models.CharField(max_length=50, null=True)),
            ],
            options={
                "db_table": "fct_stage_determination",
                "unique_together": {("fic_mis_date", "n_account_number")},
            },
        ),
    ]
