# Generated by Django 5.1 on 2025-01-14 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0027_alter_ldn_financial_instrument_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ldn_financial_instrument",
            options={
                "permissions": [
                    ("can_load_data", "Can load data"),
                    ("can_view_edit_data", "Can load data"),
                ]
            },
        ),
    ]
