# Generated by Django 5.1 on 2024-09-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "IFRS9",
            "0028_rename_n_acct_classification_skey_fct_stage_determination_n_acct_classification_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="fct_stage_determination",
            name="fic_mis_date",
            field=models.DateField(),
        ),
    ]
