# Generated by Django 5.1 on 2025-01-14 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0028_alter_ldn_financial_instrument_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fct_reporting_lines",
            options={"permissions": [("can_view_reports", "Can view reports")]},
        ),
    ]
