# Generated by Django 5.1 on 2024-09-17 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0029_alter_fct_stage_determination_fic_mis_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fct_stage_determination",
            old_name="d_revised_maturity_date",
            new_name="d_maturity_date",
        ),
    ]
