# Generated by Django 5.1 on 2025-01-14 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0029_alter_fct_reporting_lines_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fct_reporting_lines",
            options={
                "permissions": [
                    ("can_view_reports", "Can view reports"),
                    ("can_select_result_columns", "Can select columns"),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="functionexecutionstatus",
            options={
                "ordering": ["run_count", "execution_start_date"],
                "permissions": [
                    ("can_execute_run", "Can execute"),
                    ("can_monitor", "Can monitor"),
                    ("can_cancel_run", "Can cancel run"),
                ],
            },
        ),
    ]
