# Generated by Django 5.1 on 2024-09-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "IFRS9",
            "0030_rename_d_revised_maturity_date_fct_stage_determination_d_maturity_date",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="fct_stage_determination",
            name="n_account_number",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
