# Generated by Django 5.1 on 2025-01-15 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0031_alter_ldn_financial_instrument_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fct_stage_determination",
            options={"permissions": [("can_reassign_stage", "Can reassign stage")]},
        ),
        migrations.CreateModel(
            name="FSI_LGD_Term_Structure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fic_mis_date", models.DateField()),
                ("v_credit_risk_basis_cd", models.CharField(max_length=100)),
                ("n_lgd_percent", models.DecimalField(decimal_places=4, max_digits=5)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "v_lgd_term_structure_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="IFRS9.ldn_pd_term_structure",
                        to_field="v_pd_term_structure_id",
                    ),
                ),
            ],
            options={
                "db_table": "fsi_lgd_term_structure",
                "unique_together": {
                    (
                        "v_lgd_term_structure_id",
                        "fic_mis_date",
                        "v_credit_risk_basis_cd",
                    )
                },
            },
        ),
    ]
