# Generated by Django 5.1 on 2024-09-17 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0031_alter_fct_stage_determination_n_account_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fct_stage_determination",
            name="d_last_reprice_date",
        ),
    ]
