# Generated by Django 5.1 on 2025-01-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0032_alter_fct_stage_determination_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("uploaded_file", models.FileField(upload_to="support_documents/")),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "support_documents",
            },
        ),
    ]
