# Generated by Django 5.1 on 2024-09-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0032_remove_fct_stage_determination_d_last_reprice_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="FSI_CreditRating_Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credit_rating", models.CharField(max_length=50, unique=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("Stage 1", "Stage 1"),
                            ("Stage 2", "Stage 2"),
                            ("Stage 3", "Stage 3"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FSI_DPD_Stage_Mapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("half_yearly", "Half-Yearly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=50,
                    ),
                ),
                ("stage_1_threshold", models.IntegerField()),
                ("stage_2_threshold", models.IntegerField()),
                ("stage_3_threshold", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="fct_stage_determination",
            name="n_prod_desc",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fct_stage_determination",
            name="n_prod_segment",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
