# Generated by Django 5.1 on 2024-09-26 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0033_fsi_creditrating_stage_fsi_dpd_stage_mapping_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ldn_customer_info",
            old_name="v_partner_code",
            new_name="v_partner_name",
        ),
        migrations.RemoveField(
            model_name="fct_stage_determination",
            name="n_cust_type_skey",
        ),
        migrations.AddField(
            model_name="fct_stage_determination",
            name="n_partner_name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fct_stage_determination",
            name="n_party_type",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fct_stage_determination",
            name="n_pd_term_structure_desc",
            field=models.CharField(default=1, editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fct_stage_determination",
            name="n_pd_term_structure_name",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="IFRS9.fsi_product_segment",
            ),
            preserve_default=False,
        ),
    ]
