# Generated by Django 5.1 on 2024-09-26 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "IFRS9",
            "0034_rename_v_partner_code_ldn_customer_info_v_partner_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="fsi_creditrating_stage",
            table="FSI_CreditRating_Stage",
        ),
        migrations.AlterModelTable(
            name="fsi_dpd_stage_mapping",
            table="FSI_DPD_Stage_Mapping",
        ),
        migrations.AlterModelTable(
            name="tablemetadata",
            table="TableMetadata",
        ),
    ]
