# Generated by Django 5.1 on 2024-09-26 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0035_alter_fsi_creditrating_stage_table_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="fsi_interest_method",
            table="Fsi_Interest_Method",
        ),
        migrations.AlterModelTable(
            name="fsi_llfp_app_preferences",
            table="FSI_LLFP_APP_PREFERENCES",
        ),
        migrations.AlterModelTable(
            name="ldn_payment_schedule",
            table="Ldn_Payment_Schedule",
        ),
    ]
