# Generated by Django 5.1 on 2024-09-26 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0036_alter_fsi_interest_method_table_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="ldn_bank_product_info",
            table="Ldn_Bank_Product_Info",
        ),
    ]
