# Generated by Django 5.1 on 2024-09-27 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0037_alter_ldn_bank_product_info_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ldn_customer_rating_detail",
            name="v_credit_reason_code",
        ),
        migrations.RemoveField(
            model_name="ldn_customer_rating_detail",
            name="v_data_origin",
        ),
        migrations.RemoveField(
            model_name="ldn_customer_rating_detail",
            name="v_rating_src_code",
        ),
    ]
