# Generated by Django 5.1 on 2024-09-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0039_alter_fct_stage_determination_n_pd_term_structure_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoolingPeriodDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("v_amrt_term_unit", models.CharField(max_length=2)),
                ("n_cooling_period_days", models.IntegerField()),
            ],
            options={
                "db_table": "FSI_Cooling_Period_Definition",
            },
        ),
        migrations.AddField(
            model_name="fct_stage_determination",
            name="d_cooling_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fct_stage_determination",
            name="n_cooling_period_duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fct_stage_determination",
            name="n_in_cooling_period_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fct_stage_determination",
            name="n_target_ifrs_stage_skey",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
