# Generated by Django 5.1 on 2024-09-28 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0040_coolingperioddefinition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ldn_pd_term_structure_dtl",
            name="v_pd_term_structure_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="IFRS9.ldn_pd_term_structure",
                to_field="v_pd_term_structure_id",
            ),
        ),
    ]
