# Generated by Django 5.1 on 2024-09-28 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0041_alter_ldn_pd_term_structure_dtl_v_pd_term_structure_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ldn_pd_term_structure_dtl",
            unique_together={
                ("v_pd_term_structure_id", "fic_mis_date", "v_credit_risk_basis_cd")
            },
        ),
        migrations.RemoveField(
            model_name="ldn_pd_term_structure_dtl",
            name="n_period_applicable",
        ),
        migrations.RemoveField(
            model_name="ldn_pd_term_structure_dtl",
            name="v_data_source_code",
        ),
        migrations.RemoveField(
            model_name="ldn_pd_term_structure_dtl",
            name="v_scenario_cd",
        ),
    ]
