# Generated by Django 5.1 on 2024-09-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0042_alter_ldn_pd_term_structure_dtl_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fct_stage_determination",
            name="n_pd_percent",
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="ldn_financial_instrument",
            name="n_curr_payment_recd",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="ldn_financial_instrument",
            name="v_acct_rating_movement",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
