# Generated by Django 5.1 on 2024-09-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0043_fct_stage_determination_n_pd_percent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fct_stage_determination",
            name="n_curr_payment_recd",
        ),
    ]
