# Generated by Django 5.1 on 2024-09-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0044_remove_fct_stage_determination_n_curr_payment_recd"),
    ]

    operations = [
        migrations.CreateModel(
            name="Credit_Rating_Code_Band",
            fields=[
                (
                    "v_rating_code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("v_rating_desc", models.CharField(max_length=100)),
                ("fic_mis_date", models.DateField()),
            ],
            options={
                "db_table": "credit_rating_code_band",
            },
        ),
        migrations.CreateModel(
            name="Dim_Delinquency_Band",
            fields=[
                ("fic_mis_date", models.DateField()),
                (
                    "n_delq_band_code",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("v_delq_band_desc", models.CharField(max_length=60)),
                ("n_delq_lower_value", models.PositiveIntegerField()),
                ("n_delq_upper_value", models.PositiveIntegerField()),
            ],
            options={
                "db_table": "dim_delinquency_band",
            },
        ),
    ]
