# Generated by Django 5.1 on 2024-09-28 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0045_credit_rating_code_band_dim_delinquency_band"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fct_stage_determination",
            old_name="n_delq_band_skey",
            new_name="n_delq_band_code",
        ),
    ]
