# Generated by Django 5.1 on 2024-09-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "IFRS9",
            "0046_rename_n_delq_band_skey_fct_stage_determination_n_delq_band_code",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="credit_rating_code_band",
            table="dim_credit_rating_code_band",
        ),
    ]
