# Generated by Django 5.1 on 2024-09-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0047_alter_credit_rating_code_band_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dim_delinquency_band",
            name="n_delq_band_code",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="dim_delinquency_band",
            name="v_delq_band_desc",
            field=models.CharField(max_length=20),
        ),
    ]
