# Generated by Django 5.1 on 2024-09-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0048_alter_dim_delinquency_band_n_delq_band_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dim_delinquency_band",
            name="v_amrt_term_unit",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="dim_delinquency_band",
            name="v_delq_band_desc",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
