# Generated by Django 5.1 on 2024-09-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0049_dim_delinquency_band_v_amrt_term_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fct_stage_determination",
            name="n_delq_band_code",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
