# Generated by Django 5.1 on 2024-09-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0051_fsi_expected_cashflow_management_fee_added_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dim_Run",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latest_run_skey", models.BigIntegerField(default=1)),
            ],
            options={
                "db_table": "dim_run",
            },
        ),
    ]
