# Generated by Django 5.1 on 2024-09-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0052_dim_run"),
    ]

    operations = [
        migrations.AddField(
            model_name="fsi_expected_cashflow",
            name="n_exposure_at_default",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=22, null=True
            ),
        ),
    ]
