# Generated by Django 5.1 on 2024-09-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0053_fsi_expected_cashflow_n_exposure_at_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="fsi_expected_cashflow",
            name="n_accrued_interest",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=22, null=True
            ),
        ),
    ]
