# Generated by Django 5.1 on 2024-09-30 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0054_fsi_expected_cashflow_n_accrued_interest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fsi_financial_cash_flow_cal",
            name="n_cash_flow_fwd_pv",
        ),
        migrations.RemoveField(
            model_name="fsi_financial_cash_flow_cal",
            name="n_forward_exposure_amt",
        ),
        migrations.RemoveField(
            model_name="fsi_financial_cash_flow_cal",
            name="n_interest_rate_cd",
        ),
        migrations.RemoveField(
            model_name="fsi_financial_cash_flow_cal",
            name="n_per_period_loss_pv",
        ),
    ]
