# Generated by Django 5.1 on 2024-10-01 19:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0056_remove_fsi_financial_cash_flow_cal_n_per_period_loss_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="credit_rating_code_band",
            name="fic_mis_date",
        ),
        migrations.RemoveField(
            model_name="dim_delinquency_band",
            name="fic_mis_date",
        ),
        migrations.AddField(
            model_name="credit_rating_code_band",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="dim_delinquency_band",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="coolingperioddefinition",
            name="v_amrt_term_unit",
            field=models.CharField(
                choices=[
                    ("M", "Monthly"),
                    ("Q", "Quarterly"),
                    ("H", "Half-Yearly"),
                    ("Y", "Yearly"),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="fsi_dpd_stage_mapping",
            name="payment_frequency",
            field=models.CharField(
                choices=[
                    ("M", "Monthly"),
                    ("Q", "Quarterly"),
                    ("H", "Half-Yearly"),
                    ("Y", "Yearly"),
                ],
                max_length=50,
            ),
        ),
    ]
