# Generated by Django 5.1 on 2024-10-02 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0057_remove_credit_rating_code_band_fic_mis_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ldn_pd_term_structure",
            name="n_pd_term_frequency",
        ),
        migrations.RemoveField(
            model_name="ldn_pd_term_structure",
            name="v_data_source_code",
        ),
    ]
