# Generated by Django 5.1 on 2024-10-02 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0058_remove_ldn_pd_term_structure_n_pd_term_frequency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fsi_llfp_app_preferences",
            name="llfp_bucket_length",
        ),
    ]
