# Generated by Django 5.1 on 2024-10-02 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0059_remove_fsi_llfp_app_preferences_llfp_bucket_length"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ldn_lgd_term_structure",
            name="v_data_source_code",
        ),
    ]
