# Generated by Django 5.1 on 2024-10-02 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0062_dim_run_date_dim_run_last_run_skey_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dim_run",
            name="last_run_skey",
        ),
    ]
