# Generated by Django 5.1 on 2024-10-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0063_remove_dim_run_last_run_skey"),
    ]

    operations = [
        migrations.CreateModel(
            name="ECLMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method_name",
                    models.CharField(
                        choices=[
                            ("forward_exposure", "Forward Exposure Methodology"),
                            ("cash_flow", "Cash Flow Calculations Methodology"),
                            ("simple_ead", "Simple EAD Methodology"),
                        ],
                        default="forward_exposure",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("uses_discounting", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dim_ecl_method",
            },
        ),
    ]
