# Generated by Django 5.1 on 2024-10-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0064_eclmethod"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportColumnConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_name", models.CharField(max_length=100)),
                ("selected_columns", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "dim_report_column_map",
            },
        ),
    ]
