# Generated by Django 5.1 on 2024-10-06 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0066_function_process_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FunctionExecutionStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("execution_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Ongoing", "Ongoing"),
                            ("Success", "Success"),
                            ("Failed", "Failed"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("process_run_id", models.CharField(max_length=255, unique=True)),
                ("run_count", models.PositiveIntegerField()),
                (
                    "function",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="IFRS9.function"
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="IFRS9.process"
                    ),
                ),
            ],
            options={
                "db_table": "function_execution_status",
                "ordering": ["run_count", "execution_date"],
            },
        ),
    ]
