# Generated by Django 5.1 on 2024-10-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0067_functionexecutionstatus"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="functionexecutionstatus",
            table="dim_function_execution_status",
        ),
    ]
