# Generated by Django 5.1 on 2024-10-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0068_alter_functionexecutionstatus_table"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="functionexecutionstatus",
            constraint=models.UniqueConstraint(
                fields=("execution_date", "process_run_id"),
                name="unique_execution_process",
            ),
        ),
    ]
