# Generated by Django 5.1 on 2024-10-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0069_functionexecutionstatus_unique_execution_process"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="functionexecutionstatus",
            name="unique_execution_process",
        ),
        migrations.AddConstraint(
            model_name="functionexecutionstatus",
            constraint=models.UniqueConstraint(
                fields=("execution_date", "process_run_id", "function"),
                name="unique_execution_process",
            ),
        ),
    ]
