# Generated by Django 5.1 on 2024-10-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "IFRS9",
            "0070_remove_functionexecutionstatus_unique_execution_process_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="functionexecutionstatus",
            name="process_run_id",
            field=models.CharField(max_length=50),
        ),
    ]
