# Generated by Django 5.1 on 2024-10-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0071_alter_functionexecutionstatus_process_run_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="functionexecutionstatus",
            name="reporting_date",
            field=models.DateField(null=True),
        ),
    ]
