# Generated by Django 5.1 on 2024-10-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0072_functionexecutionstatus_reporting_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="functionexecutionstatus",
            name="execution_order",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
