# Generated by Django 5.1 on 2024-10-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0073_functionexecutionstatus_execution_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "function_name",
                    models.CharField(
                        choices=[("INFO", "Info"), ("ERROR", "Error")], max_length=10
                    ),
                ),
                (
                    "log_level",
                    models.CharField(
                        choices=[("INFO", "Info"), ("ERROR", "Error")], max_length=10
                    ),
                ),
                ("message", models.TextField()),
                ("status", models.CharField(default="SUCCESS", max_length=10)),
            ],
            options={
                "verbose_name": "Log",
                "verbose_name_plural": "Logs",
                "db_table": "dim_massage_logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
