# Generated by Django 5.1 on 2024-10-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0074_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="function_name",
            field=models.CharField(
                choices=[("INFO", "Info"), ("ERROR", "Error")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="log_level",
            field=models.CharField(
                choices=[("INFO", "Info"), ("ERROR", "Error")], max_length=50
            ),
        ),
    ]
