# Generated by Django 5.1 on 2024-10-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0075_alter_log_function_name_alter_log_log_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="function_name",
            field=models.CharField(
                choices=[("INFO", "Info"), ("ERROR", "Error")], max_length=50
            ),
        ),
    ]
