# Generated by Django 5.1 on 2024-10-23 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0076_alter_log_function_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=3, unique=True)),
                ("description", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "dim_currency_code",
            },
        ),
        migrations.CreateModel(
            name="ReportingCurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="IFRS9.currencycode",
                    ),
                ),
            ],
            options={
                "db_table": "dim_reporting_currency_code",
            },
        ),
    ]
