# Generated by Django 5.1 on 2024-10-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IFRS9", "0078_dimexchangerateconf_ldn_exchange_rate_d_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="dimexchangerateconf",
            name="use_latest_exchange_rates",
            field=models.BooleanField(default=False),
        ),
    ]
